[package]
name = "tcpservice"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
log.workspace = true
thiserror.workspace = true
bincode = "1.3"
serde.workspace = true
async-trait = "0.1.73"
